# Generated by Django 2.2.28 on 2022-05-29 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grupo_Contatos',
            new_name='Grupodecontatos',
        ),
    ]
