# Generated by Django 2.2.28 on 2022-05-31 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_agenda', '0002_auto_20220529_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatos',
            name='id_grupo',
        ),
    ]
