# Generated by Django 2.2.28 on 2022-06-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agenda', '0005_auto_20220531_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
